### ISSUE TITLE
Event function

### ISSUE THREAD

**Issue by PapyPev** [CliffCloud/Leaflet.EasyButton#32]
Hello, 
If I want to create a series of button from a loop and recover the loop identifier in the event function. How can I recover the loop identifier?

Example :
```javascript
for (var i = 0; i < 3; i++) {
  L.easyButton( '<span class="easy-button">&equiv;</span>', 
    function(){
      alert(i);
   }).addTo(map);
};
```
Regards,
Pev

**Comment by PapyPev** [comment]
Problem temporarily solved by a dirty solution: Move the identifier in the title button.
```javascript
for (var i = 0; i < 3; i++) {
  var ident = i.toString();
  L.easyButton( '<span class="easy-button">&equiv;</span>', 
    function(){
      alert(this.button.title);
    }, ident
  ).addTo(map);
};
```
But I'm still interested in a better solution :)
Pev

**Comment by atstp** [comment]
Yeah, unfortunately everything about this will be slightly dirty because current JavaScript doesn't have block scope.  What you'll have to do is force scope with a function.

so this (not working): 

    for (var i = 0; i < 3; i++) {
      L.easyButton( '<span class="easy-button">&equiv;</span>', 
        function(){
          alert(i);
       }).addTo(map);
    }

can be reorganized into this(working):

    for (var i = 0; i < 3; i++) {
      buildAndAddAButton(i)
    };

    function buildAndAddAButton(alertVal){
      L.easyButton( '<span class="easy-button">&equiv;</span>', 
        function(){
          alert(alertVal);
       }).addTo(map);
    }

### extra info:

there are other approaches out there for this (either with an [IIFE](http://adripofjavascript.com/blog/drips/emulating-block-scope-in-javascript.html) or `bind`), but this is the most readable/maintainable.  

sometime in the future you'll be able to use `let`, but for now, its [support](http://caniuse.com/#feat=let) isn't great. 

    for(var i = 0; i < 3; i++){ // this will never work
      setTimeout(function(){
        console.log(i);
      },i * 2000);
    }

    for(let i = 0; i < 3; i++){ // this will
      setTimeout(function(){
        console.log(i);
      },i * 2000);
    }

**Comment by PapyPev** [comment]
Perfect ! Thank you so much !
That answers my questions and solves my problem at the same time :)
Wonderful explanation. As I begin in Javascript, I am happy to have this kind of response, thank you again!
