### ISSUE TITLE
Drag and drop marker from button onto map.

### ISSUE THREAD

**Issue by ipepe** [CliffCloud/Leaflet.EasyButton#36]
How to implement drag from button to map and create a marker there?

**Comment by atstp** [comment]
Are you looking specifically for drag-drop action?

Adding a marker on a button click would be a bit more straightforward and significantly easier to support across devices. 

Let me know which route you're set on going and i'll help you however i can!

**Comment by ipepe** [comment]
My test team wants drag'n'drop :(

**Comment by ipepe** [comment]
Well I thought about adding drag'n'drop feature to easy buttons but code is ~350 lines and I hoped it would be easier...

Going back to my test team case: 

We have a rails view of places/new where You add new place to app. And by default we set marker to Your location based on ip address ( currently, but we hope to add geolocation into work ). So You have map centered with marker in middle. You can drag it and when You have Your desired location You can click inside its baloon on button to get address from coordinates of that marker. You can also outside of map type into input field address and it will set marker to that position. My test team says its annoying to drag marker from their location to somewhere and they want to move that marker to desired location by drag'n'droping it

**Comment by atstp** [comment]
Just to clarify that I'm understanding correctly:

  * your page starts with a marker set on the user's location(ip based)
  * the marker's position can be changed by either dragging or input fields
  * clicking on the marker will bring up its coordinates

and the functionality you're looking for is

  * pulling a marker from the button onto the map

is that all correct, or do I have anything mixed up?

**Comment by atstp** [comment]
side note: looks like our time zones don't line up too well.  I'll check back in 10-12 hours and hopefully catch you at what looks like a more regular time for you!

**Comment by ipepe** [comment]
All correct. Just to make sure:
"pulling a marker from the button onto the map" - it would just move existing marker to a new position without a need to drag it across whole country

**Comment by atstp** [comment]
EasyButton does a bit of behind-the-scenes click management, so some of EasyButton's tools will be ignored, and other parts will need to be handled manually.

You'll want to do a few things: 

  * Build an instance of EasyButton whose states lack the `onClick` property; these states will be cosmetic, because you want `mousedown` not click (like [these](http://danielmontague.com/projects/easyButton.js/v1/examples/#many-states))
  * The EasyButton's `button` attribute will be the literal `<button>` dom element
  * Set handlers on `easyButtonInstance.button`, for `mousedown` or `drag`, whichever suits your plan better
  * Adjust the `easyButtonInstance`'s states through the button's `state` method; something like  `easyButtonInstance.state('mid-drag')`

This should give you all the upsides of EasyButton you can use, like state management and dom construction, and let you take control for the custom stuff you're shooting for. 

Good luck and let me know if there's anything I left cloudy!

**Comment by atstp** [comment]
Here's some pseudocode: 

    var placeMarker = L.marker(L.latLng(0,0))
    
    var buttonForPlaceMarker = L.easyButton({
      states:[
        {
          stateName: 'marker-out-of-bounds',
          icon: 'fa-frown-o',
          title: "you can't see the marker"
        }, {
          stateName: 'marker-in-bounds',
          icon: 'fa-smile-o'
          title: 'you can see the marker'
        }, {
          stateName: 'mid-drag',
          icon: 'fa-airplane',
          title: 'dragging'
        }
      ]
    });
    
    var buttonElement = buttonForPlaceMarker.button;
    
    
    buttonElement.addEventListener('mousedown',function(){
    
      // make the button indicate things are getting dragged
      buttonForPlaceMarker.state('mid-drag');
    
      // start handling drag-and-drop business!
      // once the mouse leaves the button and enters the map, 
      // start following the cursor with the marker
    
    });

**Comment by M1F** [comment]
Поши все нахуй со своим избатоном, пидарасы ебливые, не пишите мне больше уебаны.  02.12.2015, 10:51, "atstp" <notifications@github.com>:Here's some pseudocode:var placeMarker = L.marker(L.latLng(0,0))

var buttonForPlaceMarker = L.easyButton({
  states:[
    {
      stateName: 'marker-out-of-bounds',
      icon: 'fa-frown-o',
      title: "you can't see the marker"
    }, {
      stateName: 'marker-in-bounds',
      icon: 'fa-smile-o'
      title: 'you can see the marker'
    }, {
      stateName: 'mid-drag',
      icon: 'fa-airplane',
      title: 'dragging'
    }
  ]
});

var buttonElement = buttonForPlaceMarker.button;


buttonElement.addEventListener('mousedown',function(){

  // make the button indicate things are getting dragged
  buttonForPlaceMarker.state('mid-drag');

  // start handling drag-and-drop business!
  // once the mouse leaves the button and enters the map, 
  // start following the cursor with the marker

});

**Comment by atstp** [comment]
I closed this because of @M1F's comments (and deleted them).  

If there's anything else you need, let me know!

**Comment by M1F** [comment]
Иди хуя сосни пидарас ебучий, иж че комент ему не понравился. А мне твой спам ебливый не нравится. Нассы себе в ебач. 03.12.2015, 00:03, "atstp" <notifications@github.com>:I closed this because of @M1F's comments (and deleted them).If there's anything else you need, let me know!—Reply to this email directly or view it on GitHub.   -- ツ
