### ISSUE TITLE
Button position without using states

### ISSUE THREAD

**Issue by alex-michaud** [CliffCloud/Leaflet.EasyButton#49]
Is it possible to place a button on 'bottomright' without using states?
If so, how?

**Comment by atstp** [comment]
yeah, absolutely! (despite its omission from the docs -- sorry!)

For any argument combination, you can pass in a final options object like so:

    var positioned = L.easyButton('fa-circle', function(){
      alert('you clicked the circle')
    }, 'title', {
      position: 'bottomright'
    });
    positioned.addTo(map);

Hope it helps, and if it's lacking feel free to reopen/comment.

**Comment by atstp** [comment]
While not ideal, that _is_ expected behavior; EasyButton buillds on Leaflet defaults and what you're describing is the behavior of Leaflet's controls.

There are two simple approaches you can take mollify this:

* place all controls you want to stack in the same position (put both your easy button and an attribution control in the `bottomleft`)
* add some styles to raise your bottomleft controls over the wide bottomright attribution control:
`.leaflet-bottom.leaflet-left { padding-bottom: 100px; }`
